### ISSUE TITLE
Deprecated include in MiniAOD/MiniAODHelper/interface/MiniAODHelper.h

### ISSUE THREAD

**Issue by riga** [cms-ttH/MiniAOD#18]
Hi guys,

I'm not sure whether you use this issue tracker, but there's an error that occurs during compilation with 80X (e.g. 8_0_11):

```
bash
In file included from .../CMSSW_8_0_11/src/MiniAOD/MiniAODHelper/interface/MiniAODHelper.h:33:0,
                 from .../CMSSW_8_0_11/src/MiniAOD/SkimDilep/plugins/SkimDilep.cc:67:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_11/src/CommonTools/Utils/interface/normalizedPhi.h:6:52: fatal error: DataFormats/Math/include/normalizedPhi.h: No such file or directory
 #include "DataFormats/Math/include/normalizedPhi.h"
```

I already opened an issue in the CMSSW repo. Turned out that the include statement in [MiniAODHelper/interface/MiniAODHelper.h#L33](https://github.com/cms-ttH/MiniAOD/blob/master/MiniAODHelper/interface/MiniAODHelper.h#L33)

```
#include "CommonTools/Utils/interface/normalizedPhi.h"
```

is deprecated and should be replaced by

```
#include "DataFormats/Math/interface/normalizedPhi.h"
```

Hope that helps!

**Comment by matz-e** [comment]
Seems to be fixed on the `8_0_8` branch.
